# Built with Jekyll 3.2.0

title: Eugene Gavrilov
subtitle: Frontend Engineer
email: eugene@huncode.com
#description: |- # this means to ignore newlines until "baseurl:"
#  Source for sharing frontend projects and ideas.
#  Hire Senior Frontend Engineer for your rockstar UI project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huncode.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: huncoder
github_username:  huncode
# tagline: 'a jekyll theme for minimal editions'

# About/contact
author:
  name:              Eugene Gavrilov
  url:               https://twitter.com/huncoder
  email:             eugene@huncode.com

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: jekyll-theme-dinky


